<div class="row">
	<div class="col-md-1">
		<?=$book->getId()?>
	</div>
	<div class="col-md-2">
		<?=$book->getName()?>
	</div>
	<div class="col-md-1">
		<?=$book->getAuthor()?>
	</div>
	<div class="col-md-1">
		<?=$book->getCountry()?>
	</div>
	<div class="col-md-1">
		<?=$book->getGender()?>
	</div>
	<div class="col-md-1">
		<?=$book->getYear()?>
	</div>
	<div class="col-md-2">
		<?=$book->getEditorial()?>
	</div>
	<div class="col-md-2">
		<?=$book->getIsbn()?>
	</div>
	<div class="col-md-1">
		<?=$book->getPrice()?>
	</div>
</div>